version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=test
      - DB_HOST=db
      - DB_DIALECT=mysql
      - JWT_SECRET=your_secret_key
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "24538:24538"
